--shop report
-- in this shop report we focus on how many service or product is sold and the total revenue generated

SELECT 
    service.service_id,
    service.service_title, 
    COUNT(employee_service_record.esr_id) AS esr_count, 
    service.price
FROM 
    employee_service_record 
LEFT JOIN 
    service 
ON 
    employee_service_record.service_id = service.service_id
WHERE 
    employee_service_record.payment = 'paid'
GROUP BY 
    service.service_id,
    service.service_title, 
    service.price;

--From above code, we get esr_count, multiply it with the price will give us the subtotal revenue generated by each service type.


SELECT 
    product.prod_id,
    product.prod_name,
    COUNT(employee_product_record.epr_id) AS epr_count, 
    product.price
FROM 
    employee_product_record 
LEFT JOIN 
    product
ON 
    employee_product_record.prod_id = product.prod_id
WHERE 
    employee_product_record.payment = 'paid'
GROUP BY 
    product.prod_id,
    product.prod_name,
    product.price;

--From above code, we get epr_count, multiply it with the price will give us the subtotal revenue generated by each product type.

--Then we can find the total revenue generated by suming these values.